versin: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup docker
          command: |
            cp .env.sample .env
            docker-compose up -d --build
      - run:
          name: Setup Laravel
          command: |
            cp src/.env.example src/.env
            docker-compose run app composer install
            docker-compose run app php artisan key:generate
            docker-compose run app php artisan migrate:refresh
            docker-compose run node npm install
            docker-compose run node npm run dev
      - run:
          name: Run Sniffer
          command: |
            docker-compose run app composer sniffer
      - run:
          name: Run Test
          command: |
            docker-compose run app vendor/bin/phpunit