versin: 2
jobs:
  docker_build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - docker-laravel-app-{{ .Branch }}--{{ checksum ".circleci/config.yml" }}--{{ checksum "docker-compose.yml" }}
          paths:
            - ~/caches/images.tar
      - run:
          name: Setup docker
          command: |
            if [ ! -f ~/caches/images.tar ]; then
              cp .env.circleci .env
              docker-compose up -d --build
              mkdir -p ~/caches
              docker save $(docker images | awk 'NR>=2 && ! /^<none>/{print $1}') -o ~/caches/images.tar
            fi
      - save_cache:
          key: docker-laravel-app-{{ .Branch }}--{{ checksum ".circleci/config.yml" }}--{{ checksum "docker-compose.yml" }}
          paths:
            - ~/caches/images.tar
  test:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - docker-laravel-app-{{ .Branch }}--{{ checksum ".circleci/config.yml" }}--{{ checksum "docker-compose.yml" }}
          paths:
            - ~/caches/images.tar
      - run:
          name: docker load
          command: |
            if [[ -e ~/caches/images.tar ]]; then
              docker load -i ~/caches/images.tar
            fi
      - run:
          name: Setup Laravel
          command: |
            cp .env.circleci .env
            docker-compose run app composer install
            cp src/.env.circleci src/.env
            docker-compose run app php artisan key:generate
            docker-compose run app php artisan migrate:refresh
            docker-compose run node npm install
            docker-compose run node npm run dev
      - run:
          name: Run Sniffer
          command: |
            docker-compose run app composer sniffer
      - run:
          name: Run Test
          command: |
            docker-compose run app vendor/bin/phpunit
workflows:
  version: 2
  build_and_test:
    jobs:
      - docker_build
      - test:
          requires:
            - docker_build